In [33]:
import pandas as pd
import numpy as np
import re

In [34]:
houses = pd.read_csv("houses.csv")

In [35]:
houses.sample(5)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,...,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
856,3 Bedroom House for sale in Sector 14 Gurgaon,https://www.99acres.com/3-bhk-bedroom-independ...,Sector 14 RWA,5.51 Crore,"₹ 16,990/sq.ft.",(302 sq.m.) Plot Area,Plot area 361(301.84 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,...,"Mg Road, Sector 14 Gurgaon, Gurgaon, Haryana",4 Floors,South-West,5 to 10 Year Old,"['Sheetla Mata Mandir', 'Hanuman Mandir', 'Hsb...",Available for sale sector 14 gurgaon size 361 ...,NaN,"['High Ceiling Height', 'Maintenance Staff', '...","['Environment4 out of 5', 'Safety4 out of 5', ...",F70044510
259,1 Bedroom House for sale in Mianwali Colony,https://www.99acres.com/1-bhk-bedroom-independ...,Project Mianwali Colony,1.7 Crore,"₹ 9,444/sq.ft.",(167 sq.m.) Carpet Area,Carpet area: 1800 (167.23 sq.m.),1 Bedroom,1 Bathroom,2 Balconies,...,"Mianwali Colony, Sector 12a, Mianwali Colony, ...",1 Floors,NaN,undefined,"['Hanuman Mandir', 'Sheetla Mata Mandir', 'Lal...",Best in class property available at mianwali c...,NaN,NaN,"['Environment3.5 out of 5', 'Lifestyle4 out of...",M69654546
678,5 Bedroom House for sale in Sector 66 Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Emaar MGF Marbella,12 Crore,"₹ 38,095/sq.ft.",(293 sq.m.) Plot Area,Plot area 350(292.64 sq.m.),5 Bedrooms,6 Bathrooms,3+ Balconies,...,"Sector 66 Gurgaon, Gurgaon, Haryana",4 Floors,North-East,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",The villa is north east facing and a corner vi...,"['9 AC', '1 Chimney', 'No Bed', 'No Curtains',...","['Private Garden / Terrace', 'Maintenance Staf...","['Environment3 out of 5', 'Lifestyle4 out of 5...",P64342250
781,4 Bedroom House for sale in Sector 48 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,Vipul Tatvam Villa,8.4 Crore,"₹ 21,000/sq.ft.",(372 sq.m.) Plot Area,Plot area 4000(371.61 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,...,"Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,North,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Wishing to settle down in an individual house ...,"['5 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5...",K69830898
481,2 Bedroom House for sale in Damdma,https://www.99acres.com/2-bhk-bedroom-independ...,NaN,18 Lac,"₹ 4,000/sq.ft.",(42 sq.m.) Plot Area,Plot area 450(41.81 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,...,"Damdma, Gurgaon, Haryana",1 Floors,East,1 to 5 Year Old,NaN,"This is a 2 bhk house with plot for sale, its ...",NaN,NaN,NaN,G68099368

In [36]:
houses.drop(columns=["link" , "property_id"] , inplace=True)

In [37]:
houses = houses[houses.price != "Price on Request"]

In [38]:
def lac(x):
    if (type(x) == float):
        return x
    else:
        if(x[1] != "Lac"):
            return round (float(x[0]) , 2)
        else:
            return round(float(x[0])/100,2)

In [39]:
houses.price = houses.price.str.split(" ").apply(lac)

In [40]:
houses.rename(columns={"rate" : "price_per_sq"},inplace=True)

In [41]:
houses.price_per_sq = houses.price_per_sq.str.replace(",", "").str.replace("₹ " , "").str.replace("/sq.ft." , "").astype(float)

In [42]:
houses = houses[~houses.bedRoom.isnull()]

In [43]:
houses['bedRoom'] = houses.bedRoom.str.replace("Bedrooms" , "").str.replace("Bedroom","")

In [44]:
houses.bedRoom = houses['bedRoom'].astype(int)

In [45]:
houses['bathroom'] = houses.bathroom.str.replace("Bathrooms" , "").str.replace("Bathroom","")

In [46]:
houses.bathroom = houses.bathroom.astype(int)

In [47]:
houses.balcony = houses.balcony.str.replace("+" , "").str.replace(" Balconies","").str.replace(" Balcony", "").str.replace("No ", "0")

In [48]:
houses.balcony = houses.balcony.str.replace("No","0")

In [49]:
houses.balcony = houses.balcony.astype(int)

In [50]:
houses.society = houses.society.apply (lambda x : re.sub(r"\d+\.+\d+\s★","" , str(x))).str.strip().str.lower()

In [51]:
houses.additionalRoom.fillna("not available" , inplace=True)

C:\Users\pc\AppData\Local\Temp\ipykernel_25760\3024329639.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  houses.additionalRoom.fillna("not available" , inplace=True)

In [52]:
houses.additionalRoom = houses.additionalRoom.str.lower()

In [53]:
houses.address.fillna("Na" , inplace=True)

C:\Users\pc\AppData\Local\Temp\ipykernel_25760\1707765097.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  houses.address.fillna("Na" , inplace=True)

In [54]:
houses.head()

,property_name,society,price,price_per_sq,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,nan,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,nan,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,nan,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,nan,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [55]:
houses.noOfFloor = (
    houses.noOfFloor.str.split(" ").str.get(0)
    .str.replace("Basement" , "-1")
    .str.replace("Ground","0")
    .str.replace("Lower" , "0").str.extract(r"(\d+)")
)

In [56]:
houses.facing.fillna("Na",inplace=True)

C:\Users\pc\AppData\Local\Temp\ipykernel_25760\1073818894.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  houses.facing.fillna("Na",inplace=True)

In [57]:
houses.nearbyLocations = houses.nearbyLocations.str.lower()

In [58]:
houses.furnishDetails = houses.furnishDetails.str.lower()

In [59]:
houses.features = houses.features.str.lower()

In [60]:
houses.rating = houses.rating.str.lower()

In [61]:
houses.area = round((houses.price * 10000000) / houses.price_per_sq)

In [62]:
houses.insert(column="property_type" , value="houses",loc=2)

In [67]:
houses.society = houses.society.str.replace("nan" , "independent")

In [69]:
houses.to_csv("houses_cleaned.csv")

In [68]:
houses

,property_name,society,property_type,price,price_per_sq,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,houses,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['good earth city center 2', 'kunskapsskolan i...",Do you wish to buy an independent house in sec...,"['1 wardrobe', '1 fan', '1 exhaust fan', '1 ge...","['feng shui / vaastu compliant', 'private gard...","['environment5 out of 5', 'lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,houses,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,Na,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 water purifier', '5 fan', '1 exhaust fan',...","['private garden / terrace', 'park', 'visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,houses,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['sector 42-43 metro station', 'huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 bed', '3 fan', '10 geyser', '2 light', 'n...","['maintenance staff', 'water storage', 'visito...","['environment5 out of 5', 'lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,houses,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['sector 53-54 metro station', 'sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 water purifier', '21 fan', '1 fridge', '1 ...","['feng shui / vaastu compliant', 'private gard...","['environment4 out of 5', 'lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,houses,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['sector 42-43 metro station', 'huda city cent...",Best for investment purpose. Fully furnished b...,"['1 water purifier', '1 fridge', '12 fan', '1 ...","['maintenance staff', 'water storage', 'visito...","['environment5 out of 5', 'lifestyle5 out of 5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,4 Bedroom House for sale in Sector 26 Gurgaon,dlf city phase 1,houses,5.50,30556.0,1800.0,Plot area 200(167.23 sq.m.),4,4,3,"pooja room,study room,servant room","Sector 26 Gurgaon, Gurgaon, Haryana",2,North-East,5 to 10 Year Old,"['dlf phase 1 metro station', 'sikandarpur met...","Residential house, g block, dlf phase-1, gurga...","['10 light', 'no ac', 'no bed', 'no chimney', ...","['feng shui / vaastu compliant', 'high ceiling...",NaN
1040,3 Bedroom House for sale in DLF Phase 2,dlf city plots phase 2,houses,4.25,31481.0,1350.0,Plot area 150(125.42 sq.m.),3,2,3,study room,"DLF Phase 2, Gurgaon, Haryana",2,North,10+ Year Old,"['sahara mall', 'delhi public school', 'privat...","Residential house, k block, dlf phase-2, gurga...",NaN,"['high ceiling height', 'maintenance staff', '...","['environment5 out of 5', 'safety5 out of 5', ..."
1041,3 Bedroom House for sale in Sector 26 Gurgaon,dlf city phase 1,houses,4.50,33333.0,1350.0,Plot area 150(125.42 sq.m.),3,3,2,"study room,servant room","Sector 26 Gurgaon, Gurgaon, Haryana",2,East,5 to 10 Year Old,"['dlf phase 1 metro station', 'sikandarpur met...","Residential house, e block 150 sq.Yds , dlf ph...","['6 fan', '20 light', 'no ac', 'no bed', 'no c...","['feng shui / vaastu compliant', 'private gard...",NaN
1042,3 Bedroom House for sale in Sector 26 Gurgaon,dlf city phase 1,houses,3.25,33129.0,981.0,Plot area 109(91.14 sq.m.),3,3,3,study room,"Sector 26 Gurgaon, Gurgaon, Haryana",2,West,10+ Year Old,"['dlf phase 1 metro station', 'sikandarpur met...","Residential house, e block, dlf phase-1, gurga...","['5 fan', '16 light', 'no ac', 'no bed', 'no c...","['feng shui / vaastu compliant', 'private gard...",NaN
1043,3 Bedroom House for sale in Bissar,silverglades tarudhan valley golf resort,houses,3.60,14815.0,2430.0,Plot area 270(225.75 sq.m.),3,3,2,"pooja room,study room,servant room,others","Bissar, Gurgaon, Haryana",2,Na,5 to 10 Year Old,NaN,This 3 bhk house for sale in bissar is an idea...,"['1 water purifier', '10 fan', '1 fridge', '1 ...","['centrally air conditioned', 'water purifier'...",NaN