In [40]:
import pandas as pd

In [41]:
houses = pd.read_csv("houses_cleaned.csv" , index_col=[0])
flats = pd.read_csv("flats_cleaned.csv" , index_col=[0])

In [42]:
houses.rename(columns={"noOfFloor":"floorNum"} , inplace=True)

In [43]:
df = pd.concat([flats, houses] , ignore_index=True)

In [44]:
df = df.sample(df.shape[0], ignore_index=True)

In [45]:
df

,property_name,society,property_type,price,price_per_sq,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 113 Gurgaon,m3m capital,flats,2.00,12012.0,1665.0,Super Built up area 1665(154.68 sq.m.),3,3,2,not available,"sector 113 gurgaon , gurgaon, haryana",24.0,na,By 2023,"['phase 2 metro station', 'global foyer mall',...",We are the proud owners of this 3 bhk apartmen...,[],"['lift(s)', 'swimming pool', 'park', 'visitor ...",NaN
1,3 BHK Flat in Sector 88A Gurgaon,godrej oasis,flats,1.29,7800.0,1654.0,Super Built up area 1629(151.34 sq.m.)Carpet a...,3,3,3,"study room,others","godrej oasis, sector-88a gurgaon, sector 88a g...",5.0,na,0 to 1 Year Old,"['double infinity market', 'pataudi road', 'dw...",Godrej oasis is one of the most popular destin...,[],"['feng shui / vaastu compliant', 'intercom fac...","['green area5 out of 5', 'amenities5 out of 5'..."
2,1 BHK Flat in Sector 104 Gurgaon,zara aavaas,flats,0.20,6645.0,301.0,Built Up area: 301 (27.96 sq.m.),1,1,1,not available,"sector 104, sector 104 gurgaon, gurgaon, haryana",3.0,north-east,undefined,"['ardee mall', 'northern peripheral road', 'mp...",Best in class property available at sector 104...,NaN,NaN,"['environment4 out of 5', 'lifestyle4 out of 5..."
3,2 Bedroom House for sale in Arjun Nagar,independent,houses,0.32,7111.0,450.0,Built Up area: 450 (41.81 sq.m.)Carpet area: 3...,2,3,1,not available,"Arjun Nagar, Sector 8, Arjun Nagar, Gurgaon, H...",1.0,North-East,1 to 5 Year Old,NaN,Best in class property available at arjun naga...,NaN,NaN,"['environment4 out of 5', 'lifestyle4 out of 5..."
4,4 BHK Flat in Sector 69 Gurgaon,tulip violet,flats,1.70,8445.0,2013.0,Super Built up area 2010(186.74 sq.m.),4,4,2,not available,"701, sector 69 gurgaon, gurgaon, haryana",7.0,west,1 to 5 Year Old,"['airia mall sector 68', 'southern peripheral ...",Tulip violet is one of gurgaon's most sought a...,"['1 modular kitchen', 'no ac', 'no bed', 'no c...","['security / fire alarm', 'power back-up', 'fe...","['green area5 out of 5', 'construction4 out of..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3969,5 Bedroom House for sale in Sector 108 Gurgaon,sobha city,houses,10.50,14323.0,7331.0,Built Up area: 7331 (681.07 sq.m.),5,4,3,not available,"Sector 109, Sector 108 Gurgaon, Gurgaon, Haryana",1.0,East,undefined,"['dwarka sector 21', 'dwarka expressway', 'vas...",Most luxurious property in the vicinity sobha ...,NaN,NaN,"['environment4 out of 5', 'lifestyle4.5 out of..."
3970,3 BHK Flat in Sector 69 Gurgaon,tulip violet,flats,1.38,8972.0,1538.0,Carpet area: 1538 (142.88 sq.m.),3,3,1,not available,"sector 69 gurgaon, gurgaon, haryana",12.0,west,1 to 5 Year Old,"['airia mall sector 68', 'southern peripheral ...",Check out this 3 bhk apartment for sale in tul...,"['1 modular kitchen', 'no ac', 'no bed', 'no c...","['centrally air conditioned', 'water purifier'...","['green area5 out of 5', 'construction4 out of..."
3971,5 BHK Flat in Sector 110 Gurgaon,indiabulls enigma,flats,3.79,9895.0,3830.0,Super Built up area 3830(355.82 sq.m.),5,5,3,"servant room,others","dwarka expressway, sector 110 gurgaon, gurgaon...",4.0,south-west,1 to 5 Year Old,"['dwarka sector 21 metro station', 'gurgaon dr...",Indiabulls enigma township is a residential re...,"['8 ac', '1 modular kitchen', 'no bed', 'no ch...","['security / fire alarm', 'feng shui / vaastu ...","['environment4 out of 5', 'lifestyle4 out of 5..."
3972,3 BHK Flat in Sector 85 Gurgaon,ss the leaf,flats,1.84,7641.0,2408.0,Super Built up area 2408(223.71 sq.m.)Carpet a...,3,4,3,pooja room,"sector 85 gurgaon, gurgaon, haryana",8.0,south-east,1 to 5 Year Old,"['sapphire 83 mall', 'dwarka expressway', 'cen...","This 3 bhk flat is located in ss the leaf, whi...","['14 light', '5 ac', 'no bed', 'no chimney', '...","['centrally air conditioned', 'water purifier'...","['green area4.5 out of 5', 'construction4.5 ou..."
3973,4 BHK Flat in Sector 112 Gurgaon,experion windchants,flats,5.60,11529.0,4857.0,Super Built up area 4857(451.23 sq.m.)Built Up...,4,6,3,servant room,"0000, sector 112 gurgaon, gurgaon, haryana",15.0,north-east,5 to 10 Year Old,"['ansal plaza', 'dwaraka expressway', 'first s...",Looking for a 4 bhk property for sale in gurga...,"['5 wardrobe', '1 water purifier', '12 fan', '...","['water purifier', 'security / fire alarm', 'f...","['green area5 out of 5', 'amenities5 out of 5'..."

In [47]:
df.to_csv("gurgaon_properties_data.csv")

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3974 entries, 0 to 3973
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3974 non-null   object
 1   society          3973 non-null   object
 2   property_type    3974 non-null   object
 3   price            3954 non-null   float64
 4   price_per_sq     3954 non-null   float64
 5   area             3954 non-null   float64
 6   areaWithType     3974 non-null   object
 7   bedRoom          3974 non-null   int64
 8   bathroom         3974 non-null   int64
 9   balcony          3974 non-null   int64
 10  additionalRoom   3974 non-null   object
 11  address          3974 non-null   object
 12  floorNum         3952 non-null   float64
 13  facing           3974 non-null   object
 14  agePossession    3973 non-null   object
 15  nearbyLocations  3767 non-null   object
 16  description      3974 non-null   object
 17  furnishDetails   2940 non-null   object
 18  features         3264 non-null   object
 19  rating           3524 non-null   object
dtypes: float64(4), int64(3), object(13)
memory usage: 621.1+ KB

In [36]:
houses.info()

<class 'pandas.core.frame.DataFrame'>
Index: 977 entries, 0 to 1043
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    977 non-null    object
 1   society          403 non-null    object
 2   property_type    977 non-null    object
 3   price            958 non-null    float64
 4   price_per_sq     958 non-null    float64
 5   area             958 non-null    float64
 6   areaWithType     977 non-null    object
 7   bedRoom          977 non-null    int64
 8   bathroom         977 non-null    int64
 9   balcony          977 non-null    int64
 10  additionalRoom   977 non-null    object
 11  address          977 non-null    object
 12  floorNum         957 non-null    float64
 13  facing           977 non-null    object
 14  agePossession    977 non-null    object
 15  nearbyLocations  861 non-null    object
 16  description      977 non-null    object
 17  furnishDetails   740 non-null    object
 18  features         674 non-null    object
 19  rating           856 non-null    object
dtypes: float64(4), int64(3), object(13)
memory usage: 160.3+ KB